feature: Support ARM64 and other platforms (#12)
arduino/setup-protoc pull request #44
Opened 2022-09-27 00:41 UTC by adamchalmers

I've added unit tests, so hopefully this works :) If you approve this PR I would appreciate cutting a new release afterwards, as there's a number of projects which would like to run this on ARM.

2022-09-27 17:16 UTC, adamchalmers commented
Hmm, don't merge this, it doesn't properly detect these platforms yet.

2022-09-29 14:06 UTC, adamchalmers commented
Actually, my test wasn't actually running on those weird platforms, it was using cross-compilation. I think setup-protoc should probably let users override `os.arch()` and specify their own arch/plat in an optional Github Action input if they choose to. But I'll open a separate PR for that.

2022-11-03 18:27 UTC, adamchalmers commented
@MatteoPologruto @per1234 Hi! Could I please get a review on this?

2023-01-28 16:11 UTC, per1234 requested changes

2023-01-28 16:11 UTC, per1234 commented on src/installer.ts
> + * See https://nodejs.org/api/os.html#osplatform for possible values.
```suggestion
 * @param osArch - A string identifying operating system CPU architecture for which the Node.js binary was compiled.
 * See https://nodejs.org/api/os.html#osarch for possible values.
```

The description and reference URL were for the operating system platform/`os.platform()`, whereas this parameter is the architecture/`os.arch()`.

2023-01-28 16:11 UTC, per1234 commented on src/installer.ts
> + * See https://nodejs.org/api/os.html#osplatform for more.
```suggestion
 * @param osArch - The operating system CPU architecture for which the Node.js binary was compiled.
 * See https://nodejs.org/api/os.html#osarch for more.
```


The description and reference URL were for the operating system platform/`os.platform()`, whereas this parameter is the architecture/`os.arch()`.

2023-05-19 14:56 UTC, alessio-perugini requested changes
Thank you for your contribution! Do you mind addressing the change requested? We'd really like to merge this :nerd_face:

2023-05-19 14:56 UTC, alessio-perugini commented on __tests__/main.test.ts
> +  ];
```suggestion
    ["protoc-3.20.2-osx-x86_64.zip", "darwin", "x64"],
    ["protoc-3.20.2-win64.zip", "win32", "x64"],
    ["protoc-3.20.2-win32.zip", "win32", "x32"],
  ];
```
Do you mind adding this 2 test cases for windows?

2023-05-19 16:50 UTC, adamchalmers commented
Of course, I applied all suggestions.

2023-05-19 17:07 UTC, alessio-perugini commented
> I can't get the `prettier` check to pass, despite running `npm format`. I assume I need some particular version of prettier installed? Or some particular npm/node version?

Might be related to this:
``` 
    ["protoc-3.20.2-osx-x86_64.zip", "darwin", "x64"][
      ("protoc-3.20.2-osx-x86_64.zip", "darwin", "x64")
    ],
 ```
should be:
````
    ["protoc-3.20.2-osx-x86_64.zip", "darwin", "x64"],
    ["protoc-3.20.2-osx-x86_64.zip", "darwin", "x64"],
    ["protoc-3.20.2-win64.zip", "win32", "x64"],
  ````

2023-05-19 18:11 UTC, adamchalmers commented
OK, formatter fixed.

2023-05-19 19:16 UTC, alessio-perugini approved these changes
LGTM! :rocket:

2023-05-19 19:48 UTC, adamchalmers commented
Nice! I can't merge until @per1234 changes their review status, or an admin merges this for me.

2023-05-22 07:09 UTC, alessio-perugini commented
@adamchalmers we forgot to run `npm run build`. Can you run it and add the changes in a new commit? :pray:

2023-05-22 20:09 UTC, adamchalmers commented
Done, I got one error from `npm run build`

```
$ npm run build

> setup-protoc-action@0.0.0 build
> tsc

node_modules/keyv/src/index.d.ts:60:32 - error TS2304: Cannot find name 'AsyncGenerator'.

60  iterator(namespace?: string): AsyncGenerator<any, void, any>;
                                  ~~~~~~~~~~~~~~


Found 1 error.
```

2023-05-23 07:56 UTC, alessio-perugini commented
> Done, I got one error from `npm run build`
> 
> ```
> $ npm run build
> 
> > setup-protoc-action@0.0.0 build
> > tsc
> 
> node_modules/keyv/src/index.d.ts:60:32 - error TS2304: Cannot find name 'AsyncGenerator'.
> 
> 60  iterator(namespace?: string): AsyncGenerator<any, void, any>;
>                                   ~~~~~~~~~~~~~~
> 
> 
> Found 1 error.
> ```

It was something related to typescript version. If you rebase this on master and run again `npm run build` we should fix the issue. We're almost there :muscle:

2023-05-24 14:55 UTC, merged

2023-05-24 16:32 UTC, adamchalmers commented
Awesome, thanks for shepherding this through, Alessio.