Upgrade to node 20
arduino/setup-protoc pull request #95
Opened 2024-01-25 18:03 UTC by alessio-perugini

GitHub will deprecate the node runtime soon. ( https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)
We're bumping the node version to 20.
After merging this, must follow a bump of the major version of this action.

2024-01-26 13:03 UTC, per1234 requested changes

2024-01-26 13:03 UTC, per1234 commented on .github/workflows/check-npm-task.yml
> +      #  run: task --silent npm:validate
There is now a fix for the problem with the `npm:validate` task in the upstream "template":

https://github.com/arduino/tooling-project-assets/commit/cc6f87c1bf8cb188d5b4f258900531c4e67d301b

2024-01-29 00:08 UTC, per1234 approved these changes
Thanks Alessio!

2024-01-31 16:04 UTC, MatteoPologruto approved these changes

2024-01-31 16:04 UTC, merged

2024-01-31 18:26 UTC, kayabaNerve commented
The CI on the commit merging this appears to have failed, despite the CI here passing.

https://github.com/arduino/setup-protoc/actions/runs/7728930562/job/21070931021

Is any context/insight available on this?

2024-01-31 21:49 UTC, per1234 commented
@kayabaNerve the failure was caused by an external change to the `package.json` schema that was made between the time of the CI run for this PR and when the PR was merged.

The cause of the workflow run failure was only a defect in the project's CI system, not in the content of the project. So the workflow run failure it is nothing for users of the action to be concerned about. 

I submitted a fix with details about the problem here: https://github.com/arduino/setup-protoc/pull/96